import {
  AboutUsImg,
  SectionAbout,
  TextBox,
  BoxStyled,
  StyledSpan,
} from './About.styled';
import sprite from '../../images/sprite.svg';
import { aboutUsImages } from '../../helpers/imagesHelper';

function About() {
  return (
    <SectionAbout className="container">
      <BoxStyled>
        <h2>
          a story that started{' '}
          <StyledSpan>
            with
            <span> one simple ape</span>
          </StyledSpan>
        </h2>
        <p>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC <span>JOURNEY ON THE YACHT</span>
        </p>
      </BoxStyled>

      <TextBox>
        <svg>
          <use href={`${sprite}#icon-x`}></use>
        </svg>
        <p>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </p>
      </TextBox>
      <picture>
        <source
          srcSet={`${aboutUsImages.desktop[0]} 1x,${aboutUsImages.desktop[1]} 2x`}
          media="(min-width: 1280px)"
        />
        <source
          srcSet={`${aboutUsImages.tablet[0]} 1x,${aboutUsImages.tablet[1]} 2x`}
          media="(min-width: 768px)"
        />
        <source
          srcSet={`${aboutUsImages.mobile[0]} 1x,${aboutUsImages.mobile[1]} 2x`}
          media="(max-width: 767px)"
        />
        <AboutUsImg src={aboutUsImages.mobile[0]} alt="Monkey" />
      </picture>
    </SectionAbout>
  );
}

export default About;
